version: "3.1"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./.docker/metabase-data:/metabase-data
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
  node:
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - "postgres"
    command: "$RUN_APPLICATION"